# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:12345678@tcp(127.0.0.1:3306)/gfast-v32mandate"
        tables:          "sys_role_dept"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/system"