// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import "github.com/tiger1103/gfast/v3/internal/app/onlinemeeting/dao/internal"

// tMeetingDao is the data access object for the table t_meeting.
// You can define custom methods on it to extend its functionality as needed.
type tFileDao struct {
	*internal.TFileDao
}

var (
	// TFile is a globally accessible object for table t_meeting operations.
	TFile = tFileDao{internal.NewTFileDao()}
)

// Add your custom methods and functionality below.
